### PR TITLE
feat(release): Update SDK to use Beta API version 2023-07-11

### PR DESCRIPTION
**Pull request by deepaksibm**

### CODE REVIEW

**Comment by deepaksibm** [comment]
image
image

**Comment by deepaksibm** [comment]
NEW FEATURES

1. ListVirtualNetworkInterfaces
2. GetVirtualNetworkInterface
3. UpdateVirtualNetworkInterface
4. Added ShareMountTargetVirtualNetworkInterfacePrototype in ShareMountTargetPrototype for API CreateShareMountTarget()
5. Added TransitEncryption in ShareMountTargetPrototypeShareMountTargetByAccessControlModeSecurityGroup
6. Added AccessControlMode to SharePrototype for the API CreateShare()

**Review by astha-jain — APPROVED** [review]
looks good

**Pull request merged**
