### PR TITLE
feat(release): Update SDK to use Beta API version 2023-11-03

### PR DESCRIPTION
**Pull request by deepaksibm**

### CODE REVIEW

**Comment by deepaksibm** [comment]
```
make test-unit
go test `go list ./... | grep vpcbetav1` -v -tags=unit
=== RUN   TestVpcbetaV1
Running Suite: VpcbetaV1 Suite
==============================
Random Seed: 1698987047
Will run 2446 of 2446 specs

••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 2446 of 2446 Specs in 87.708 seconds
SUCCESS! -- 2446 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcbetaV1 (88.30s)
PASS
ok      github.com/IBM/vpc-beta-go-sdk/vpcbetav1        89.380s
```

**Comment by deepaksibm** [comment]
```
package main

import (
	"fmt"
	"log"

	"github.com/IBM/go-sdk-core/v5/core"
	"github.com/IBM/vpc-beta-go-sdk/vpcbetav1"
)

var APIKey = "APIKEY" // required, Add a valid API key here

func main() {
	// Create the IAM authenticator.
	authenticator := &core.IamAuthenticator{
		ApiKey: APIKey,
	}

	// Create the service options struct.
	options := &vpcbetav1.VpcbetaV1Options{
		Authenticator: authenticator,
	}

	// Instantiate the service.
	vpcBetaService, vpcServiceErr := vpcbetav1.NewVpcbetaV1(options)

	if vpcServiceErr != nil {
		log.Fatalf("Error creating VPC Service.")
	}

	// Retrieve the list of regions for your account.
	listRegionsOptions := &vpcbetav1.ListRegionsOptions{}
	_, detailedResponse, err := vpcBetaService.ListRegions(listRegionsOptions)
	if err != nil {
		log.Fatalf("Failed to list the regions: %s and the response is: %s", err.Error(), detailedResponse)
	}

	fmt.Println(detailedResponse)
	listVpcs := &vpcbetav1.ListVpcsOptions{}
	_, detr, err := vpcBetaService.ListVpcs(listVpcs)
	fmt.Println(detr)

	listVolumeProfiles := &vpcbetav1.ListVolumeProfilesOptions{}
	_, resp, err := vpcBetaService.ListVolumeProfiles(listVolumeProfiles)
	fmt.Println(resp)

	volumeProfileIdentityModel := &vpcbetav1.VolumeProfileIdentityByName{
		Name: core.StringPtr("sdp"),
	}

	zoneIdentityModel := &vpcbetav1.ZoneIdentityByName{
		Name: core.StringPtr("us-east-2"),
	}

	volumePrototypeModel := &vpcbetav1.VolumePrototypeVolumeByCapacity{
		Profile:  volumeProfileIdentityModel,
		Zone:     zoneIdentityModel,
		Capacity: core.Int64Ptr(int64(100)),
		Name:     core.StringPtr("beta-sdk-test-volume"),
	}

	createVolumeOptions := vpcBetaService.NewCreateVolumeOptions(
		volumePrototypeModel,
	)

	_, resp, err = vpcBetaService.CreateVolume(createVolumeOptions)
	if err != nil {
		panic(err)
	}
	fmt.Println(resp)
	// volumeId := *volume.ID

	// getVolume := &vpcbetav1.GetVolumeOptions{
	// 	ID: &volumeId,
	// }
	// volume, _, err = vpcBetaService.GetVolume(getVolume)
	// if err != nil {
	// 	panic(err)
	// }
	// fmt.Println(*volume.Name)
	// log.Printf("Regions: %+v", regions)

}

```

**Comment by deepaksibm** [comment]
```
&{POST https://us-east.iaas.cloud.ibm.com/v1/volumes?generation=2&maturity=beta&version=2023-11-07 HTTP/1.1 1 1 map[Accept:[application/json] Content-Type:[application/json] User-Agent:[vpc-beta-go-sdk-0.1.0 (arch=arm64; os=darwin; go.version=go1.20.3)]] {{"name":"beta-sdk-test-volume","profile":{"name":"sdp"},"zone":{"name":"us-east-2"},"capacity":100}
} 0x10522cfd0 100 [] false us-east.iaas.cloud.ibm.com map[] map[] <nil> map[]   <nil> <nil> <nil> 0x14000096000}
{
    "StatusCode": 201,
    "Headers": {
        "Cache-Control": [
            "max-age=0, no-cache, no-store, must-revalidate"
        ],
        "Cf-Cache-Status": [
            "DYNAMIC"
        ],
        "Cf-Ray": [
            "822f507499e40690-MAA"
        ],
        "Content-Length": [
            "1122"
        ],
        "Content-Type": [
            "application/json; charset=utf-8"
        ],
        "Date": [
            "Wed, 08 Nov 2023 16:50:20 GMT"
        ],
        "Etag": [
            "W/\"07168f064b0f6c2543fde8e35b0ce37d6da22450a7d9fdef4d0c224388f0c168\""
        ],
        "Expires": [
            "-1"
        ],
        "Pragma": [
            "no-cache"
        ],
        "Server": [
            "cloudflare"
        ],
        "Strict-Transport-Security": [
            "max-age=31536000; includeSubDomains"
        ],
        "Vary": [
            "Accept-Encoding"
        ],
        "X-Content-Type-Options": [
            "nosniff"
        ],
        "X-Correlation-Id": [
            "e12bf804-82fc-4f67-ad1a-e055cb9eff67"
        ],
        "X-Request-Id": [
            "33afa5966546b4a9b9ec1275410ad14f"
        ],
        "X-Xss-Protection": [
            "1; mode=block"
        ]
    },
    "Result": {
        "active": false,
        "attachment_state": "unattached",
        "bandwidth": 13,
        "busy": false,
        "capacity": 100,
        "created_at": "2023-11-08T16:50:20.000Z",
        "crn": "crn:v1:bluemix:public:is:us-east-2:a/7f75c7b025e54bc5635f754b2f888665::volume:r014-eaa0f214-34ac-4b84-acfd-bc2a70942e16",
        "encryption": "provider_managed",
        "health_reasons": [],
        "health_state": "inapplicable",
        "href": "https://us-east.iaas.cloud.ibm.com/v1/volumes/r014-eaa0f214-34ac-4b84-acfd-bc2a70942e16",
        "id": "r014-eaa0f214-34ac-4b84-acfd-bc2a70942e16",
        "iops": 100,
        "name": "beta-sdk-test-volume",
        "profile": {
            "href": "https://us-east.iaas.cloud.ibm.com/v1/volume/profiles/sdp",
            "name": "sdp"
        },
        "resource_group": {
            "href": "https://resource-controller.cloud.ibm.com/v2/resource_groups/bdd96715c2a44f2bb60df4ff14a543f5",
            "id": "bdd96715c2a44f2bb60df4ff14a543f5",
            "name": "Default"
        },
        "resource_type": "volume",
        "status": "pending",
        "status_reasons": [],
        "user_tags": [],
        "volume_attachments": [],
        "zone": {
            "href": "https://us-east.iaas.cloud.ibm.com/v1/regions/us-east/zones/us-east-2",
            "name": "us-east-2"
        }
    },
    "RawResult": null
}

```

**Comment by deepaksibm** [comment]
## New Features
1. Acadia defined performance profile for block volume storage

**Comment by deepaksibm** [comment]
```
&{POST https://us-east.iaas.cloud.ibm.com/v1/volumes?generation=2&maturity=beta&version=2023-11-22 HTTP/1.1 1 1 map[Accept:[application/json] Content-Type:[application/json] User-Agent:[vpc-beta-go-sdk-0.7.0 (arch=arm64; os=darwin; go.version=go1.20.3)] X-Request-Id:[6bf8be59-f567-4c11-8392-495e6fa07902]] {{"name":"beta-sdk-test-volume","profile":{"name":"sdp"},"zone":{"name":"us-east-2"},"capacity":100}
} 0x104bd9110 100 [] false us-east.iaas.cloud.ibm.com map[] map[] <nil> map[]   <nil> <nil> <nil> 0x1400002e070}
{
    "StatusCode": 201,
    "Headers": {
        "Cache-Control": [
            "max-age=0, no-cache, no-store, must-revalidate"
        ],
        "Cf-Cache-Status": [
            "DYNAMIC"
        ],
        "Cf-Ray": [
            "82a889d3fe4ff43d-BOM"
        ],
        "Content-Length": [
            "1122"
        ],
        "Content-Type": [
            "application/json; charset=utf-8"
        ],
        "Date": [
            "Thu, 23 Nov 2023 09:55:49 GMT"
        ],
        "Etag": [
            "W/\"07168f064b0f6c2543fde8e35b0ce37d6da22450a7d9fdef4d0c224388f0c168\""
        ],
        "Expires": [
            "-1"
        ],
        "Pragma": [
            "no-cache"
        ],
        "Server": [
            "cloudflare"
        ],
        "Strict-Transport-Security": [
            "max-age=31536000; includeSubDomains"
        ],
        "Vary": [
            "Accept-Encoding"
        ],
        "X-Content-Type-Options": [
            "nosniff"
        ],
        "X-Correlation-Id": [
            "3c9bc2b2-8399-4e54-9f8a-172b5dd0d8fa"
        ],
        "X-Request-Id": [
            "6bf8be59-f567-4c11-8392-495e6fa07902"
        ],
        "X-Xss-Protection": [
            "1; mode=block"
        ]
    },
    "Result": {
        "active": false,
        "attachment_state": "unattached",
        "bandwidth": 13,
        "busy": false,
        "capacity": 100,
        "created_at": "2023-11-23T09:55:49.000Z",
        "crn": "crn:v1:bluemix:public:is:us-east-2:a/7f75c7b025e54bc5635f754b2f888665::volume:r014-a0b0093b-2620-4151-b54e-5c97ade2334f",
        "encryption": "provider_managed",
        "health_reasons": [],
        "health_state": "inapplicable",
        "href": "https://us-east.iaas.cloud.ibm.com/v1/volumes/r014-a0b0093b-2620-4151-b54e-5c97ade2334f",
        "id": "r014-a0b0093b-2620-4151-b54e-5c97ade2334f",
        "iops": 100,
        "name": "beta-sdk-test-volume",
        "profile": {
            "href": "https://us-east.iaas.cloud.ibm.com/v1/volume/profiles/sdp",
            "name": "sdp"
        },
        "resource_group": {
            "href": "https://resource-controller.cloud.ibm.com/v2/resource_groups/bdd96715c2a44f2bb60df4ff14a543f5",
            "id": "bdd96715c2a44f2bb60df4ff14a543f5",
            "name": "Default"
        },
        "resource_type": "volume",
        "status": "pending",
        "status_reasons": [],
        "user_tags": [],
        "volume_attachments": [],
        "zone": {
            "href": "https://us-east.iaas.cloud.ibm.com/v1/regions/us-east/zones/us-east-2",
            "name": "us-east-2"
        }
    },
    "RawResult": null
}
```

**Review by sumitkumartiwari — APPROVED** [review]

**Pull request merged**
