### PR TITLE
feat(release): Update SDK to use Beta API version 2024-03-12

### PR DESCRIPTION
**Pull request by deepaksibm**

### CODE REVIEW

**Comment by deepaksibm** [comment]
###New Features

- Support for confidential compute sgx mode (ConfidentialComputeMode) and (EnableSecureBoot) in InstancePrototype
- Support for private path load balancer
- Support for private path service gateways

**Comment by deepaksibm** [comment]
```
make test-examples

GetLoadBalancerProfile() result:
•
ListLoadBalancers() result:
•
CreateLoadBalancer() result:
•
GetLoadBalancer() result:
•
UpdateLoadBalancer() result:
•
GetLoadBalancerStatistics() result:
•
ListLoadBalancerListeners() result:
•
CreateLoadBalancerListener() result:
•
GetLoadBalancerListener() result:
•
UpdateLoadBalancerListener() result:
•
ListLoadBalancerListenerPolicies() result:
•
CreateLoadBalancerListenerPolicy() result:
•
GetLoadBalancerListenerPolicy() result:
•
UpdateLoadBalancerListenerPolicy() result:
•
ListLoadBalancerListenerPolicyRules() result:
•
CreateLoadBalancerListenerPolicyRule() result:
•
GetLoadBalancerListenerPolicyRule() result:
•
UpdateLoadBalancerListenerPolicyRule() result:
•
ListLoadBalancerPools() result:
•
CreateLoadBalancerPool() result:
•
GetLoadBalancerPool() result:
•
UpdateLoadBalancerPool() result:
•
ListLoadBalancerPoolMembers() result:
•
CreateLoadBalancerPoolMember() result:
•
GetLoadBalancerPoolMember() result:
•
UpdateLoadBalancerPoolMember() result:
•
ReplaceLoadBalancerPoolMembers() result:
•
DeleteLoadBalancerPoolMember() response status code: 204
•
DeleteLoadBalancerPool() response status code: 204
•
DeleteLoadBalancerListenerPolicyRule() response status code: 204
•
DeleteLoadBalancerListenerPolicy() response status code: 204
•
DeleteLoadBalancerListener() response status code: 204
•
DeleteLoadBalancer() response status code: 204
•
ListPrivatePathServiceGateways() result:
•
CreatePrivatePathServiceGateway() result:
•
GetPrivatePathServiceGateway() result:
•
UpdatePrivatePathServiceGateway() result:
•
ListPrivatePathServiceGatewayAccountPolicies() result:
•
CreatePrivatePathServiceGatewayAccountPolicy() result:
•
GetPrivatePathServiceGatewayAccountPolicy() result:
•
UpdatePrivatePathServiceGatewayAccountPolicy() result:
•
ListEndpointGateways() result:
•
CreateEndpointGateway() result:
•
ListPrivatePathServiceGatewayEndpointGatewayBindings() result:
•
GetPrivatePathServiceGatewayEndpointGatewayBinding() result:
••••
ListEndpointGatewayIps() result:
•
AddEndpointGatewayIP() result:
•
GetEndpointGateway() result:
•
GetEndpointGatewayIP() result:
•
UpdateEndpointGateway() result:
•
RemoveEndpointGatewayIP() response status code: 204
•
DeleteEndpointGateway() response status code: 204
•
ListFlowLogCollectors() result:
•
CreateFlowLogCollector() result:
•
GetFlowLogCollector() result:
•
UpdateFlowLogCollector() result:
•
DeleteFlowLogCollector() response status code: 204
•
DeleteBareMetalServerNetworkInterface() response status code: 204
•
```



```
make test-unit
go test `go list ./... | grep vpcbetav1` -v -tags=unit
=== RUN   TestVpcbetaV1
Running Suite: VpcbetaV1 Suite
==============================
Random Seed: 1710408631
Will run 2790 of 2790 specs

••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 2790 of 2790 Specs in 100.655 seconds
SUCCESS! -- 2790 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcbetaV1 (101.61s)
PASS
ok      github.com/IBM/vpc-beta-go-sdk/vpcbetav1        103.819s
```

**Review by uibm — APPROVED** [review]
lgtm

**Pull request merged**
